trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  DOCKER_USERNAME: "bhattyash32"
  DOCKER_PASSWORD: "Alkatraz@0"  # Store this in Azure DevOps secrets
  IMAGE_NAME: "my-app"
  IMAGE_TAG: "$(Build.BuildId)"
  FULL_IMAGE_NAME: "bhattyash32/$(IMAGE_NAME):$(IMAGE_TAG)"
  DEPENDENCY_TRACK_URL: "http://144.126.254.101:8080"
  DEPENDENCY_TRACK_API_KEY: "odt_usj4SjhVV2VVZFTqQPgHVLNQre730kqY"

stages:
- stage: Build
  displayName: "Build and Push Container Image"
  jobs:
  - job: BuildImage
    displayName: "Build and Push Image to Docker Hub"
    steps:
    - script: |
        echo "$(DOCKER_PASSWORD)" | docker login -u "$(DOCKER_USERNAME)" --password-stdin
      displayName: "Login to Docker Hub"

    - script: |
        docker build -t $(FULL_IMAGE_NAME) .
      displayName: "Build Docker Image"

    - script: |
        docker push $(FULL_IMAGE_NAME)
      displayName: "Push Image to Docker Hub"

- stage: KBOM
  displayName: "Generate KBOM and Scan for Vulnerabilities"
  jobs:
  - job: GenerateKBOM
    displayName: "Generate SBOM and Vulnerability Reports"
    steps:
    - script: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
        syft version
      displayName: "Install Syft"

    - script: |
        syft $(FULL_IMAGE_NAME) -o json > sbom.json
      displayName: "Generate SBOM with Syft"

    - script: |
        curl -sSfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
        trivy --version
      displayName: "Install Trivy"

    - script: |
        trivy image --format json -o trivy-report.json $(FULL_IMAGE_NAME)
      displayName: "Scan Image for Vulnerabilities with Trivy"

    - task: PublishBuildArtifacts@1
      displayName: "Upload SBOM and Trivy Reports"
      inputs:
        pathToPublish: "$(System.DefaultWorkingDirectory)"
        artifactName: "KBOM-Reports"

- stage: UploadDependencyTrack
  displayName: "Upload Reports to OWASP Dependency-Track"
  dependsOn: KBOM
  jobs:
  - job: UploadReports
    displayName: "Upload SBOM & Vulnerability Reports"
    steps:
    - script: |
        curl -X POST -H "X-Api-Key: $(DEPENDENCY_TRACK_API_KEY)" -F "file=@sbom.json" $(DEPENDENCY_TRACK_URL)/api/v1/bom
      displayName: "Upload SBOM to OWASP Dependency-Track"

    - script: |
        curl -X POST -H "X-Api-Key: $(DEPENDENCY_TRACK_API_KEY)" -F "file=@trivy-report.json" $(DEPENDENCY_TRACK_URL)/api/v1/vulnerability
      displayName: "Upload Vulnerabilities to OWASP Dependency-Track"
